name: build deb

on:
  push:
    paths:
      - '.github/workflows/build.yml'  # build.yaml
      - 'control' 
    branches:
      - 'main'  # main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4.2.2
        with:
          submodules: true

      - name: Check cache
        run: |
          echo upstream_heads=git ls-remote https://github.com/roothide/theos | head -n 1 | cut -f 1-git ls-remote https://github.com/theos/sdks | head -n 1 | cut -f 1 >> $GITHUB_ENV

      - name: Use cache
        id: cache
        uses: actions/cache@v4.2.1
        with:
          path: ${{ github.workspace }}/theos
          key: ${{ runner.os }}-${{ env.upstream_heads }}

      - name: Prepare Theos
        uses: axs66/theos-action@main

      - name: Setup GNU Make
        run: |
          echo "$(brew --prefix)/opt/make/libexec/gnubin" >> $GITHUB_PATH

      - name: Build package
        run: |
          mkdir -p packages
          rm -f packages/*.deb
          make package FINALPACKAGE=1 -j$(sysctl -n hw.ncpu)
          make package THEOS_PACKAGE_SCHEME=rootless FINALPACKAGE=1 -j$(sysctl -n hw.ncpu)
          make package THEOS_PACKAGE_SCHEME=roothide FINALPACKAGE=1 -j$(sysctl -n hw.ncpu)

      - name: Show generated debs
        run: ls -lh packages/

      - name: Upload specific Deb packages
        uses: actions/upload-artifact@v4.6.0
        with:
          name: TGExtra
          path: packages/*.deb
